Repository ShadowShardTools/EditorGUI-Plus, pull requests merged in 2024-06, with the labels that each got.

#7 Enhancement/1 centralize methods into editor
  ShadowShardEditor/Assets/ShadowShard/Editor/PopupEditor.cs
  ShadowShardEditor/Assets/ShadowShard/Editor/Range.meta
  ShadowShardEditor/Assets/ShadowShard/Editor/Range/FloatRange.cs
  ShadowShardEditor/Assets/ShadowShard/Editor/Range/FloatRange.cs.meta
  ShadowShardEditor/Assets/ShadowShard/Editor/Range/IntRange.cs
  ShadowShardEditor/Assets/ShadowShard/Editor/Range/IntRange.cs.meta
  ShadowShardEditor/Assets/ShadowShard/Editor/ShadowShardEditor.cs
  ShadowShardEditor/Assets/ShadowShard/Editor/SliderEditor.cs
  ShadowShardEditor/Assets/ShadowShard/Editor/TextureEditor.cs
  ShadowShardEditor/Assets/ShadowShard/Editor/ToggleEditor.cs
  ShadowShardEditor/Assets/ShadowShard/Editor/VectorEditor.cs
Labels: enhancement

#9 Feature/4 add new methods
  ShadowShardEditor/Assets/ShadowShard/Editor/EditorUtils.cs
  ShadowShardEditor/Assets/ShadowShard/Editor/EditorUtils.cs.meta
  ShadowShardEditor/Assets/ShadowShard/Editor/GroupEditor.cs
  ShadowShardEditor/Assets/ShadowShard/Editor/GroupEditor.cs.meta
  ShadowShardEditor/Assets/ShadowShard/Editor/ObjectEditor.cs
  ShadowShardEditor/Assets/ShadowShard/Editor/ObjectEditor.cs.meta
  ShadowShardEditor/Assets/ShadowShard/Editor/PopupEditor.cs
  ShadowShardEditor/Assets/ShadowShard/Editor/RPUtils.cs
  ShadowShardEditor/Assets/ShadowShard/Editor/ShadowShardEditor.cs
  ShadowShardEditor/Assets/ShadowShard/Editor/SliderEditor.cs
  ShadowShardEditor/Assets/ShadowShard/Editor/TextEditor.cs
  ShadowShardEditor/Assets/ShadowShard/Editor/TextEditor.cs.meta
  ShadowShardEditor/Assets/ShadowShard/Editor/TextureEditor.cs
  ShadowShardEditor/Assets/ShadowShard/Editor/ToggleEditor.cs
  ShadowShardEditor/Assets/ShadowShard/Editor/Vector3Param.cs
  ShadowShardEditor/Assets/ShadowShard/Editor/Vector3Param.cs.meta
  ShadowShardEditor/Assets/ShadowShard/Editor/Vector4Param.cs
  ShadowShardEditor/Assets/ShadowShard/Editor/Vector4Param.cs.meta
  ShadowShardEditor/Assets/ShadowShard/Editor/VectorEditor.cs
Labels: enhancement, feature

#10 Enhancement/3 refactor draw methods
  ShadowShardEditor/Assets/ShadowShard/Editor/PopupEditor.cs
  ShadowShardEditor/Assets/ShadowShard/Editor/Section.meta
  ShadowShardEditor/Assets/ShadowShard/Editor/Section/HeaderScope.cs
  ShadowShardEditor/Assets/ShadowShard/Editor/Section/HeaderScope.cs.meta
  ShadowShardEditor/Assets/ShadowShard/Editor/Section/ISection.cs
  ShadowShardEditor/Assets/ShadowShard/Editor/Section/ISection.cs.meta
  ShadowShardEditor/Assets/ShadowShard/Editor/ShaderGUI/BaseShaderGUI.cs
  ShadowShardEditor/Assets/ShadowShard/Editor/ShaderGUI/MaterialSection.cs
  ShadowShardEditor/Assets/ShadowShard/Editor/ShaderGUI/MaterialSection.cs.meta
  ShadowShardEditor/Assets/ShadowShard/Editor/ShaderGUI/Section/ISection.cs
  ShadowShardEditor/Assets/ShadowShard/Editor/SliderEditor.cs
  ShadowShardEditor/Assets/ShadowShard/Editor/TextEditor.cs
  ShadowShardEditor/Assets/ShadowShard/Editor/TextureEditor.cs
  ShadowShardEditor/Assets/ShadowShard/Editor/ToggleEditor.cs
  ShadowShardEditor/Assets/ShadowShard/Editor/VectorEditor.cs
Labels: enhancement

#14 Enhancement/13 reunite materialeditor and editor
  ShadowShardEditor/Assets/ShadowShard/Editor/Enums.meta
  ShadowShardEditor/Assets/ShadowShard/Editor/Enums/Vector2Param.cs
  ShadowShardEditor/Assets/ShadowShard/Editor/Enums/Vector2Param.cs.meta
  ShadowShardEditor/Assets/ShadowShard/Editor/Enums/Vector3Param.cs
  ShadowShardEditor/Assets/ShadowShard/Editor/Enums/Vector3Param.cs.meta
  ShadowShardEditor/Assets/ShadowShard/Editor/Enums/Vector4Param.cs
  ShadowShardEditor/Assets/ShadowShard/Editor/Enums/Vector4Param.cs.meta
  ShadowShardEditor/Assets/ShadowShard/Editor/GroupEditor.cs
  ShadowShardEditor/Assets/ShadowShard/Editor/MaterialEditor.meta
  ShadowShardEditor/Assets/ShadowShard/Editor/MaterialEditor/AssetDataExtensions.cs
  ShadowShardEditor/Assets/ShadowShard/Editor/MaterialEditor/AssetDataExtensions.cs.meta
  ShadowShardEditor/Assets/ShadowShard/Editor/MaterialEditor/AssetObject.meta
  ShadowShardEditor/Assets/ShadowShard/Editor/MaterialEditor/AssetObject/IMaterialAssetObject.cs
  ShadowShardEditor/Assets/ShadowShard/Editor/MaterialEditor/AssetObject/IMaterialAssetObject.cs.meta
  ShadowShardEditor/Assets/ShadowShard/Editor/MaterialEditor/AssetObject/MaterialAssetObject.cs
  ShadowShardEditor/Assets/ShadowShard/Editor/MaterialEditor/AssetObject/MaterialAssetObject.cs.meta
  ShadowShardEditor/Assets/ShadowShard/Editor/MaterialEditor/AssetObject/MaterialExternalReferences.cs
  ShadowShardEditor/Assets/ShadowShard/Editor/MaterialEditor/AssetObject/MaterialExternalReferences.cs.meta
  ShadowShardEditor/Assets/ShadowShard/Editor/MaterialEditor/GlobalKeywordsService.cs
  ShadowShardEditor/Assets/ShadowShard/Editor/MaterialEditor/GlobalKeywordsService.cs.meta
  ShadowShardEditor/Assets/ShadowShard/Editor/MaterialEditor/ShaderGUI.meta
  ShadowShardEditor/Assets/ShadowShard/Editor/MaterialEditor/ShaderGUI/BaseShaderGUI.cs
  ShadowShardEditor/Assets/ShadowShard/Editor/MaterialEditor/ShaderGUI/BaseShaderGUI.cs.meta
  ShadowShardEditor/Assets/ShadowShard/Editor/MaterialEditor/ShaderGUI/IFeature.cs
  ShadowShardEditor/Assets/ShadowShard/Editor/MaterialEditor/ShaderGUI/IFeature.cs.meta
  ShadowShardEditor/Assets/ShadowShard/Editor/MaterialEditor/ShaderGUI/MaterialSection.cs
  ShadowShardEditor/Assets/ShadowShard/Editor/MaterialEditor/ShaderGUI/MaterialSection.cs.meta
  ShadowShardEditor/Assets/ShadowShard/Editor/MaterialEditor/ShaderGUI/Property.cs
  ShadowShardEditor/Assets/ShadowShard/Editor/MaterialEditor/ShaderGUI/Property.cs.meta
  ShadowShardEditor/Assets/ShadowShard/Editor/MaterialEditor/ShaderGUI/PropertyFinder.cs
  ShadowShardEditor/Assets/ShadowShard/Editor/MaterialEditor/ShaderGUI/PropertyFinder.cs.meta
  ShadowShardEditor/Assets/ShadowShard/Editor/MaterialEditor/ShadowShardMaterialEditor.cs
  ShadowShardEditor/Assets/ShadowShard/Editor/MaterialEditor/ShadowShardMaterialEditor.cs.meta
  ShadowShardEditor/Assets/ShadowShard/Editor/ObjectEditor.cs
  ShadowShardEditor/Assets/ShadowShard/Editor/PopupEditor.cs
  ShadowShardEditor/Assets/ShadowShard/Editor/PropertyService.cs
  ShadowShardEditor/Assets/ShadowShard/Editor/PropertyService.cs.meta
  ShadowShardEditor/Assets/ShadowShard/Editor/ShadowShardEditor.cs
  ShadowShardEditor/Assets/ShadowShard/Editor/SliderEditor.cs
  ShadowShardEditor/Assets/ShadowShard/Editor/TextEditor.cs
  ShadowShardEditor/Assets/ShadowShard/Editor/TextureEditor.cs
  ShadowShardEditor/Assets/ShadowShard/Editor/ToggleEditor.cs
  ShadowShardEditor/Assets/ShadowShard/Editor/VectorEditor.cs
Labels: enhancement, feature

#19 Added VectorIntEditor, fixed VectorEditor overloads
  ShadowShardEditor/Assets/ShadowShard/Editor/MaterialEditor/ShadowShardMaterialEditor.cs
  ShadowShardEditor/Assets/ShadowShard/Editor/PropertyService.cs
  ShadowShardEditor/Assets/ShadowShard/Editor/ShadowShardEditor.cs
  ShadowShardEditor/Assets/ShadowShard/Editor/VectorIntEditor.cs
  ShadowShardEditor/Assets/ShadowShard/Editor/VectorIntEditor.cs.meta
Labels: feature

#26 Valerii deineka/enhancement/18 add sealed keyword to all classes without inheriotors
  ShadowShardEditor/Assets/ManualTesting/StandardEditor/Code/Editor/TestStandardEditorWindow.cs
  ShadowShardEditor/Assets/ManualTesting/StandardEditor/Code/TestSciptableObject.cs
  ShadowShardEditor/Assets/ShadowShard/Editor/Data.meta
  ShadowShardEditor/Assets/ShadowShard/Editor/Data/Enums.meta
  ShadowShardEditor/Assets/ShadowShard/Editor/Data/Enums/Vector2Param.cs
  ShadowShardEditor/Assets/ShadowShard/Editor/Data/Enums/Vector2Param.cs.meta
  ShadowShardEditor/Assets/ShadowShard/Editor/Data/Enums/Vector3Param.cs
  ShadowShardEditor/Assets/ShadowShard/Editor/Data/Enums/Vector3Param.cs.meta
  ShadowShardEditor/Assets/ShadowShard/Editor/Data/Enums/Vector4Param.cs
  ShadowShardEditor/Assets/ShadowShard/Editor/Data/Enums/Vector4Param.cs.meta
  ShadowShardEditor/Assets/ShadowShard/Editor/Data/Range.meta
  ShadowShardEditor/Assets/ShadowShard/Editor/Data/Range/FloatRange.cs
  ShadowShardEditor/Assets/ShadowShard/Editor/Data/Range/FloatRange.cs.meta
  ShadowShardEditor/Assets/ShadowShard/Editor/Data/Range/IntRange.cs
  ShadowShardEditor/Assets/ShadowShard/Editor/Data/Range/IntRange.cs.meta
  ShadowShardEditor/Assets/ShadowShard/Editor/Data/Range/Vector2IntRange.cs
  ShadowShardEditor/Assets/ShadowShard/Editor/Data/Range/Vector2IntRange.cs.meta
  ShadowShardEditor/Assets/ShadowShard/Editor/Data/Range/Vector2Range.cs
  ShadowShardEditor/Assets/ShadowShard/Editor/Data/Range/Vector2Range.cs.meta
  ShadowShardEditor/Assets/ShadowShard/Editor/Data/Range/Vector3IntRange.cs
  ShadowShardEditor/Assets/ShadowShard/Editor/Data/Range/Vector3IntRange.cs.meta
  ShadowShardEditor/Assets/ShadowShard/Editor/Data/Range/Vector3Range.cs
  ShadowShardEditor/Assets/ShadowShard/Editor/Data/Range/Vector3Range.cs.meta
  ShadowShardEditor/Assets/ShadowShard/Editor/Data/Range/Vector4Range.cs
  ShadowShardEditor/Assets/ShadowShard/Editor/Data/Range/Vector4Range.cs.meta
  ShadowShardEditor/Assets/ShadowShard/Editor/EditorModules.meta
  ShadowShardEditor/Assets/ShadowShard/Editor/EditorModules/GroupEditor.cs
  ShadowShardEditor/Assets/ShadowShard/Editor/EditorModules/GroupEditor.cs.meta
  ShadowShardEditor/Assets/ShadowShard/Editor/EditorModules/ObjectEditor.cs
  ShadowShardEditor/Assets/ShadowShard/Editor/EditorModules/ObjectEditor.cs.meta
  ShadowShardEditor/Assets/ShadowShard/Editor/EditorModules/PopupEditor.cs
  ShadowShardEditor/Assets/ShadowShard/Editor/EditorModules/PopupEditor.cs.meta
  ShadowShardEditor/Assets/ShadowShard/Editor/EditorModules/PropertyService.cs
  ShadowShardEditor/Assets/ShadowShard/Editor/EditorModules/PropertyService.cs.meta
  ShadowShardEditor/Assets/ShadowShard/Editor/EditorModules/SliderEditor.cs
  ShadowShardEditor/Assets/ShadowShard/Editor/EditorModules/SliderEditor.cs.meta
  ShadowShardEditor/Assets/ShadowShard/Editor/EditorModules/TextEditor.cs
  ShadowShardEditor/Assets/ShadowShard/Editor/EditorModules/TextEditor.cs.meta
  ShadowShardEditor/Assets/ShadowShard/Editor/EditorModules/TextureEditor.cs
  ShadowShardEditor/Assets/ShadowShard/Editor/EditorModules/TextureEditor.cs.meta
  ShadowShardEditor/Assets/ShadowShard/Editor/EditorModules/ToggleEditor.cs
  ShadowShardEditor/Assets/ShadowShard/Editor/EditorModules/ToggleEditor.cs.meta
  ShadowShardEditor/Assets/ShadowShard/Editor/EditorModules/VectorEditor.cs
  ShadowShardEditor/Assets/ShadowShard/Editor/EditorModules/VectorEditor.cs.meta
  ShadowShardEditor/Assets/ShadowShard/Editor/EditorModules/VectorIntEditor.cs
  ShadowShardEditor/Assets/ShadowShard/Editor/EditorModules/VectorIntEditor.cs.meta
  ShadowShardEditor/Assets/ShadowShard/Editor/EditorModules/VectorsExtensions.cs
  ShadowShardEditor/Assets/ShadowShard/Editor/EditorModules/VectorsExtensions.cs.meta
  ShadowShardEditor/Assets/ShadowShard/Editor/IShadowShardEditor.cs
  ShadowShardEditor/Assets/ShadowShard/Editor/IShadowShardEditor.cs.meta
  ShadowShardEditor/Assets/ShadowShard/Editor/MaterialEditor/IShadowShardMaterialEditor.cs
  ShadowShardEditor/Assets/ShadowShard/Editor/MaterialEditor/IShadowShardMaterialEditor.cs.meta
  ShadowShardEditor/Assets/ShadowShard/Editor/MaterialEditor/ShadowShardMaterialEditor.cs
  ShadowShardEditor/Assets/ShadowShard/Editor/ShadowShardEditor.cs
Labels: enhancement

#27 Valerii deineka/feature/23 invoke action on endcheck
  ShadowShardEditor/Assets/ShadowShard/Editor/EditorModules/PopupEditor.cs
  ShadowShardEditor/Assets/ShadowShard/Editor/EditorModules/SliderEditor.cs
  ShadowShardEditor/Assets/ShadowShard/Editor/EditorModules/SliderIntEditor.cs
  ShadowShardEditor/Assets/ShadowShard/Editor/EditorModules/SliderIntEditor.cs.meta
  ShadowShardEditor/Assets/ShadowShard/Editor/EditorModules/TextEditor.cs
  ShadowShardEditor/Assets/ShadowShard/Editor/EditorModules/TextureEditor.cs
  ShadowShardEditor/Assets/ShadowShard/Editor/EditorModules/ToggleEditor.cs
  ShadowShardEditor/Assets/ShadowShard/Editor/EditorModules/VectorEditor.cs
  ShadowShardEditor/Assets/ShadowShard/Editor/EditorModules/VectorIntEditor.cs
  ShadowShardEditor/Assets/ShadowShard/Editor/IShadowShardEditor.cs
  ShadowShardEditor/Assets/ShadowShard/Editor/IShadowShardEditor.cs.meta
  ShadowShardEditor/Assets/ShadowShard/Editor/MaterialEditor/IShadowShardMaterialEditor.cs
  ShadowShardEditor/Assets/ShadowShard/Editor/MaterialEditor/IShadowShardMaterialEditor.cs.meta
  ShadowShardEditor/Assets/ShadowShard/Editor/MaterialEditor/ShadowShardMaterialEditor.cs
  ShadowShardEditor/Assets/ShadowShard/Editor/ShadowShardEditor.cs
Labels: enhancement, feature

#28 Added ScrollView
  ShadowShardEditor/Assets/ShadowShard/Editor/EditorModules/GroupEditor.cs
  ShadowShardEditor/Assets/ShadowShard/Editor/ShadowShardEditor.cs
Labels: feature

#29 Added CurveEditor
  ShadowShardEditor/Assets/ShadowShard/Editor/EditorModules/CurveEditor.cs
  ShadowShardEditor/Assets/ShadowShard/Editor/EditorModules/CurveEditor.cs.meta
  ShadowShardEditor/Assets/ShadowShard/Editor/EditorModules/ToggleEditor.cs
  ShadowShardEditor/Assets/ShadowShard/Editor/ShadowShardEditor.cs
Labels: feature

#31 Renamed files, fixed assembly
  ShadowShardEditor/Assets/EditorGUIPlus/EditorGUIPlus.asmdef
  ShadowShardEditor/Assets/EditorGUIPlus/EditorGUIPlus.asmdef.meta
  ShadowShardEditor/Assets/EditorGUIPlus/EditorGUIPlus.cs
  ShadowShardEditor/Assets/EditorGUIPlus/EditorGUIPlus.cs.meta
  ShadowShardEditor/Assets/EditorGUIPlus/IEditorGUIPlus.cs
  ShadowShardEditor/Assets/EditorGUIPlus/IEditorGUIPlus.cs.meta
  ShadowShardEditor/Assets/EditorGUIPlus/MaterialEditor/IMaterialEditorGUIPlus.cs
  ShadowShardEditor/Assets/EditorGUIPlus/MaterialEditor/IMaterialEditorGUIPlus.cs.meta
  ShadowShardEditor/Assets/EditorGUIPlus/MaterialEditor/MaterialEditorGUIPlus.cs
  ShadowShardEditor/Assets/EditorGUIPlus/MaterialEditor/MaterialEditorGUIPlus.cs.meta
  ShadowShardEditor/Assets/ManualTesting/ManualTesting.asmdef
  ShadowShardEditor/Assets/ManualTesting/ManualTesting.asmdef.meta
  ShadowShardEditor/Assets/ManualTesting/StandardEditor/Code/Editor/TestStandardEditorWindow.cs
Labels: enhancement

#33 Valerii deineka/test/12 test materialeditor
  ShadowShardEditor/Assets/EditorGUIPlus/EditorGUIPlus.cs
  ShadowShardEditor/Assets/EditorGUIPlus/EditorModules/PopupEditor.cs
  ShadowShardEditor/Assets/EditorGUIPlus/EditorModules/ToggleEditor.cs
  ShadowShardEditor/Assets/EditorGUIPlus/IEditorGUIPlus.cs
  ShadowShardEditor/Assets/EditorGUIPlus/MaterialEditor/IMaterialEditorGUIPlus.cs
  ShadowShardEditor/Assets/EditorGUIPlus/MaterialEditor/KeywordsService.cs
  ShadowShardEditor/Assets/EditorGUIPlus/MaterialEditor/KeywordsService.cs.meta
  ShadowShardEditor/Assets/EditorGUIPlus/MaterialEditor/MaterialEditorGUIPlus.cs
  ShadowShardEditor/Assets/EditorGUIPlus/MaterialEditor/ShaderGUI/BaseShaderGUI.cs
  ShadowShardEditor/Assets/EditorGUIPlus/MaterialEditor/ShaderGUI/IFeature.cs
  ShadowShardEditor/Assets/EditorGUIPlus/MaterialEditor/ShaderGUI/MaterialSection.cs
  ShadowShardEditor/Assets/ManualTesting/MaterialEditor.meta
  ShadowShardEditor/Assets/ManualTesting/MaterialEditor/IntSlidersTestSection.cs
  ShadowShardEditor/Assets/ManualTesting/MaterialEditor/IntSlidersTestSection.cs.meta
  ShadowShardEditor/Assets/ManualTesting/MaterialEditor/PopupTestSection.cs
  ShadowShardEditor/Assets/ManualTesting/MaterialEditor/PopupTestSection.cs.meta
  ShadowShardEditor/Assets/ManualTesting/MaterialEditor/SlidersTestSection.cs
  ShadowShardEditor/Assets/ManualTesting/MaterialEditor/SlidersTestSection.cs.meta
  ShadowShardEditor/Assets/ManualTesting/MaterialEditor/TestMaterial.mat
  ShadowShardEditor/Assets/ManualTesting/MaterialEditor/TestMaterial.mat.meta
  ShadowShardEditor/Assets/ManualTesting/MaterialEditor/TestMaterialGUI.cs
  ShadowShardEditor/Assets/ManualTesting/MaterialEditor/TestMaterialGUI.cs.meta
  ShadowShardEditor/Assets/ManualTesting/MaterialEditor/TestShader.shader
  ShadowShardEditor/Assets/ManualTesting/MaterialEditor/TestShader.shader.meta
  ShadowShardEditor/Assets/ManualTesting/MaterialEditor/TextureTestSection.cs
  ShadowShardEditor/Assets/ManualTesting/MaterialEditor/TextureTestSection.cs.meta
  ShadowShardEditor/Assets/ManualTesting/MaterialEditor/ToggleTestSection.cs
  ShadowShardEditor/Assets/ManualTesting/MaterialEditor/ToggleTestSection.cs.meta
  ShadowShardEditor/Assets/ManualTesting/MaterialEditor/VectorIntTestSection.cs
  ShadowShardEditor/Assets/ManualTesting/MaterialEditor/VectorIntTestSection.cs.meta
  ShadowShardEditor/Assets/ManualTesting/MaterialEditor/VectorTestSection.cs
  ShadowShardEditor/Assets/ManualTesting/MaterialEditor/VectorTestSection.cs.meta
  ShadowShardEditor/Assets/ManualTesting/StandardEditor/Code/Editor/TestStandardEditorWindow.cs
  ShadowShardEditor/Assets/Readme.asset
  ShadowShardEditor/Assets/Readme.asset.meta
  ShadowShardEditor/Assets/Scenes/SampleScene.unity
  ShadowShardEditor/Assets/TutorialInfo/Icons.meta
  ShadowShardEditor/Assets/TutorialInfo/Icons/URP.png
  ShadowShardEditor/Assets/TutorialInfo/Icons/URP.png.meta
  ShadowShardEditor/Assets/TutorialInfo/Layout.wlt
  ShadowShardEditor/Assets/TutorialInfo/Layout.wlt.meta
  ShadowShardEditor/Assets/TutorialInfo/Scripts.meta
  ShadowShardEditor/Assets/TutorialInfo/Scripts/Editor.meta
  ShadowShardEditor/Assets/TutorialInfo/Scripts/Editor/ReadmeEditor.cs
  ShadowShardEditor/Assets/TutorialInfo/Scripts/Editor/ReadmeEditor.cs.meta
  ShadowShardEditor/Assets/TutorialInfo/Scripts/Readme.cs
  ShadowShardEditor/Assets/TutorialInfo/Scripts/Readme.cs.meta
Labels: enhancement

#35 Fixed and tested MaterialAssetObject
  ShadowShardEditor/Assets/EditorGUIPlus/EditorModules/ObjectEditor.cs
  ShadowShardEditor/Assets/EditorGUIPlus/MaterialEditor/AssetDataExtensions.cs
  ShadowShardEditor/Assets/EditorGUIPlus/MaterialEditor/AssetObject/MaterialAssetObject.cs
  ShadowShardEditor/Assets/EditorGUIPlus/MaterialEditor/AssetObject/MaterialExternalReferences.cs
  ShadowShardEditor/Assets/EditorGUIPlus/MaterialEditor/IMaterialEditorGUIPlus.cs
  ShadowShardEditor/Assets/EditorGUIPlus/MaterialEditor/IMaterialEditorGUIPlus.cs.meta
  ShadowShardEditor/Assets/EditorGUIPlus/MaterialEditor/MaterialEditorGUIPlus.cs
  ShadowShardEditor/Assets/ManualTesting/MaterialEditor/ObjectTestSection.cs
  ShadowShardEditor/Assets/ManualTesting/MaterialEditor/ObjectTestSection.cs.meta
  ShadowShardEditor/Assets/ManualTesting/MaterialEditor/PopupTestSection.cs
  ShadowShardEditor/Assets/ManualTesting/MaterialEditor/Test Profile 1.asset
  ShadowShardEditor/Assets/ManualTesting/MaterialEditor/Test Profile 1.asset.meta
  ShadowShardEditor/Assets/ManualTesting/MaterialEditor/Test Profile.asset
  ShadowShardEditor/Assets/ManualTesting/MaterialEditor/Test Profile.asset.meta
  ShadowShardEditor/Assets/ManualTesting/MaterialEditor/TestMaterial.mat
  ShadowShardEditor/Assets/ManualTesting/MaterialEditor/TestMaterialGUI.cs
  ShadowShardEditor/Assets/ManualTesting/MaterialEditor/TestProfile.cs
  ShadowShardEditor/Assets/ManualTesting/MaterialEditor/TestProfile.cs.meta
  ShadowShardEditor/Assets/ManualTesting/MaterialEditor/TestShader.shader
Labels: enhancement, test

#37 Valerii deineka/feature/32 readme
  Documentation/Images/EditorGUIPlusMainHeader.png
  README.md
Labels: feature

#40 Added ConstructedSection
  ShadowShardEditor/Assets/EditorGUIPlus/MaterialEditor/ShaderGUI/BaseShaderGUI.cs
  ShadowShardEditor/Assets/EditorGUIPlus/MaterialEditor/ShaderGUI/ConstructedSection.cs
  ShadowShardEditor/Assets/EditorGUIPlus/MaterialEditor/ShaderGUI/ConstructedSection.cs.meta
  ShadowShardEditor/Assets/EditorGUIPlus/MaterialEditor/ShaderGUI/MaterialSection.cs
  ShadowShardEditor/Assets/ManualTesting/MaterialEditor/ObjectTestSection.cs
  ShadowShardEditor/Assets/ManualTesting/MaterialEditor/TestMaterial.mat
  ShadowShardEditor/Assets/ManualTesting/MaterialEditor/TestMaterialGUI.cs
Labels: enhancement, feature

#42 Valerii deineka/enhancement/38 improve readme
  README.md
Labels: enhancement, feature

#44 Valerii deineka/feature/43 add more editors from editorguilayout
  ShadowShardEditor/Assets/EditorGUIPlus/Data/Enums/ToggleAlign.cs
  ShadowShardEditor/Assets/EditorGUIPlus/Data/Enums/ToggleAlign.cs.meta
  ShadowShardEditor/Assets/EditorGUIPlus/Data/Range/DoubleRange.cs
  ShadowShardEditor/Assets/EditorGUIPlus/Data/Range/DoubleRange.cs.meta
  ShadowShardEditor/Assets/EditorGUIPlus/Data/Range/LongRange.cs
  ShadowShardEditor/Assets/EditorGUIPlus/Data/Range/LongRange.cs.meta
  ShadowShardEditor/Assets/EditorGUIPlus/EditorGUIPlus.cs
  ShadowShardEditor/Assets/EditorGUIPlus/EditorModules/ColorEditor.cs
  ShadowShardEditor/Assets/EditorGUIPlus/EditorModules/ColorEditor.cs.meta
  ShadowShardEditor/Assets/EditorGUIPlus/EditorModules/GroupEditor.cs
  ShadowShardEditor/Assets/EditorGUIPlus/EditorModules/MessageEditor.cs
  ShadowShardEditor/Assets/EditorGUIPlus/EditorModules/MessageEditor.cs.meta
  ShadowShardEditor/Assets/EditorGUIPlus/EditorModules/PopupEditor.cs
  ShadowShardEditor/Assets/EditorGUIPlus/EditorModules/TextEditor.cs
  ShadowShardEditor/Assets/EditorGUIPlus/EditorModules/ToggleEditor.cs
  ShadowShardEditor/Assets/EditorGUIPlus/EditorModules/VectorEditor.cs
  ShadowShardEditor/Assets/EditorGUIPlus/EditorModules/VectorIntEditor.cs
  ShadowShardEditor/Assets/EditorGUIPlus/IEditorGUIPlus.cs
  ShadowShardEditor/Assets/EditorGUIPlus/IEditorGUIPlus.cs.meta
  ShadowShardEditor/Assets/EditorGUIPlus/MaterialEditor/MaterialEditorGUIPlus.cs
  ShadowShardEditor/Assets/EditorGUIPlus/Scopes/BuildTargetSelectionScope.cs
  ShadowShardEditor/Assets/EditorGUIPlus/Scopes/BuildTargetSelectionScope.cs.meta
Labels: feature

#46 Fixed ToggleGroup, removed indented scope
  ShadowShardEditor/Assets/EditorGUIPlus/EditorGUIPlus.cs
  ShadowShardEditor/Assets/EditorGUIPlus/EditorModules/GroupEditor.cs
  ShadowShardEditor/Assets/EditorGUIPlus/MaterialEditor/MaterialEditorGUIPlus.cs
  ShadowShardEditor/Assets/EditorGUIPlus/Scopes/BuildTargetSelectionScope.cs
  ShadowShardEditor/Assets/EditorGUIPlus/Scopes/DisabledScope.cs
  ShadowShardEditor/Assets/EditorGUIPlus/Scopes/GroupScope.cs
  ShadowShardEditor/Assets/EditorGUIPlus/Scopes/IntendedDisabledScope.cs
  ShadowShardEditor/Assets/EditorGUIPlus/Scopes/IntendedDisabledScope.cs.meta
  ShadowShardEditor/Assets/EditorGUIPlus/Scopes/IntendedScope.cs
  ShadowShardEditor/Assets/EditorGUIPlus/Scopes/IntendedScope.cs.meta
  ShadowShardEditor/Assets/EditorGUIPlus/Scopes/ScrollableScope.cs
  ShadowShardEditor/Assets/EditorGUIPlus/Scopes/Section/HeaderScope.cs
  ShadowShardEditor/Assets/ManualTesting/StandardEditor/Code/Editor/TestStandardEditorWindow.cs
Labels: bug

#48 Remove unused using's
  ShadowShardEditor/Assets/EditorGUIPlus/EditorModules/ObjectEditor.cs
  ShadowShardEditor/Assets/EditorGUIPlus/EditorModules/PopupEditor.cs
  ShadowShardEditor/Assets/EditorGUIPlus/EditorModules/ToggleEditor.cs
  ShadowShardEditor/Assets/EditorGUIPlus/EditorModules/VectorEditor.cs
  ShadowShardEditor/Assets/EditorGUIPlus/Scopes/BuildTargetSelectionScope.cs
  ShadowShardEditor/Assets/EditorGUIPlus/Scopes/DisabledScope.cs
  ShadowShardEditor/Assets/EditorGUIPlus/Scopes/GroupScope.cs
  ShadowShardEditor/Assets/EditorGUIPlus/Scopes/ScrollableScope.cs
Labels: enhancement

#50 Feature/49 add draw methods without tproperty
  ShadowShardEditor/Assets/EditorGUIPlus/BaseEditorGUIPlus.cs
  ShadowShardEditor/Assets/EditorGUIPlus/BaseEditorGUIPlus.cs.meta
  ShadowShardEditor/Assets/EditorGUIPlus/EditorGUIPlus.cs
  ShadowShardEditor/Assets/EditorGUIPlus/EditorModules/Base.meta
  ShadowShardEditor/Assets/EditorGUIPlus/EditorModules/Base/ColorEditor.cs
  ShadowShardEditor/Assets/EditorGUIPlus/EditorModules/Base/ColorEditor.cs.meta
  ShadowShardEditor/Assets/EditorGUIPlus/EditorModules/Base/CurveEditor.cs
  ShadowShardEditor/Assets/EditorGUIPlus/EditorModules/Base/CurveEditor.cs.meta
  ShadowShardEditor/Assets/EditorGUIPlus/EditorModules/Base/ObjectEditor.cs
  ShadowShardEditor/Assets/EditorGUIPlus/EditorModules/Base/ObjectEditor.cs.meta
  ShadowShardEditor/Assets/EditorGUIPlus/EditorModules/Base/PopupEditor.cs
  ShadowShardEditor/Assets/EditorGUIPlus/EditorModules/Base/PopupEditor.cs.meta
  ShadowShardEditor/Assets/EditorGUIPlus/EditorModules/Base/SliderEditor.cs
  ShadowShardEditor/Assets/EditorGUIPlus/EditorModules/Base/SliderEditor.cs.meta
  ShadowShardEditor/Assets/EditorGUIPlus/EditorModules/Base/SliderIntEditor.cs
  ShadowShardEditor/Assets/EditorGUIPlus/EditorModules/Base/SliderIntEditor.cs.meta
  ShadowShardEditor/Assets/EditorGUIPlus/EditorModules/Base/TextEditor.cs
  ShadowShardEditor/Assets/EditorGUIPlus/EditorModules/Base/TextEditor.cs.meta
  ShadowShardEditor/Assets/EditorGUIPlus/EditorModules/Base/TextureEditor.cs
  ShadowShardEditor/Assets/EditorGUIPlus/EditorModules/Base/TextureEditor.cs.meta
  ShadowShardEditor/Assets/EditorGUIPlus/EditorModules/Base/ToggleEditor.cs
  ShadowShardEditor/Assets/EditorGUIPlus/EditorModules/Base/ToggleEditor.cs.meta
  ShadowShardEditor/Assets/EditorGUIPlus/EditorModules/Base/VectorEditor.cs
  ShadowShardEditor/Assets/EditorGUIPlus/EditorModules/Base/VectorEditor.cs.meta
  ShadowShardEditor/Assets/EditorGUIPlus/EditorModules/Base/VectorIntEditor.cs
  ShadowShardEditor/Assets/EditorGUIPlus/EditorModules/Base/VectorIntEditor.cs.meta
  ShadowShardEditor/Assets/EditorGUIPlus/EditorModules/PropertyBased.meta
  ShadowShardEditor/Assets/EditorGUIPlus/EditorModules/PropertyBased/ColorEditor.cs
  ShadowShardEditor/Assets/EditorGUIPlus/EditorModules/PropertyBased/ColorEditor.cs.meta
  ShadowShardEditor/Assets/EditorGUIPlus/EditorModules/PropertyBased/CurveEditor.cs
  ShadowShardEditor/Assets/EditorGUIPlus/EditorModules/PropertyBased/CurveEditor.cs.meta
  ShadowShardEditor/Assets/EditorGUIPlus/EditorModules/PropertyBased/ObjectEditor.cs
  ShadowShardEditor/Assets/EditorGUIPlus/EditorModules/PropertyBased/ObjectEditor.cs.meta
  ShadowShardEditor/Assets/EditorGUIPlus/EditorModules/PropertyBased/PopupEditor.cs
  ShadowShardEditor/Assets/EditorGUIPlus/EditorModules/PropertyBased/PopupEditor.cs.meta
  ShadowShardEditor/Assets/EditorGUIPlus/EditorModules/PropertyBased/SliderEditor.cs
  ShadowShardEditor/Assets/EditorGUIPlus/EditorModules/PropertyBased/SliderEditor.cs.meta
  ShadowShardEditor/Assets/EditorGUIPlus/EditorModules/PropertyBased/SliderIntEditor.cs
  ShadowShardEditor/Assets/EditorGUIPlus/EditorModules/PropertyBased/SliderIntEditor.cs.meta
  ShadowShardEditor/Assets/EditorGUIPlus/EditorModules/PropertyBased/TextEditor.cs
  ShadowShardEditor/Assets/EditorGUIPlus/EditorModules/PropertyBased/TextEditor.cs.meta
  ShadowShardEditor/Assets/EditorGUIPlus/EditorModules/PropertyBased/TextureEditor.cs
  ShadowShardEditor/Assets/EditorGUIPlus/EditorModules/PropertyBased/TextureEditor.cs.meta
  ShadowShardEditor/Assets/EditorGUIPlus/EditorModules/PropertyBased/ToggleEditor.cs
  ShadowShardEditor/Assets/EditorGUIPlus/EditorModules/PropertyBased/ToggleEditor.cs.meta
  ShadowShardEditor/Assets/EditorGUIPlus/EditorModules/PropertyBased/VectorEditor.cs
  ShadowShardEditor/Assets/EditorGUIPlus/EditorModules/PropertyBased/VectorEditor.cs.meta
  ShadowShardEditor/Assets/EditorGUIPlus/EditorModules/PropertyBased/VectorIntEditor.cs
  ShadowShardEditor/Assets/EditorGUIPlus/EditorModules/PropertyBased/VectorIntEditor.cs.meta
  ShadowShardEditor/Assets/EditorGUIPlus/MaterialEditor/MaterialEditorGUIPlus.cs
  ShadowShardEditor/Assets/ManualTesting/StandardEditor/Data/TestData.asset
  ShadowShardEditor/Packages/manifest.json
  ShadowShardEditor/Packages/packages-lock.json
Labels: enhancement, feature

#52 Enhancement/51 remove ref from baseeditorguiplus
  ShadowShardEditor/Assets/EditorGUIPlus/BaseEditorGUIPlus.cs
  ShadowShardEditor/Assets/EditorGUIPlus/EditorGUIPlus.cs
  ShadowShardEditor/Assets/EditorGUIPlus/EditorModules/Base/ColorEditor.cs
  ShadowShardEditor/Assets/EditorGUIPlus/EditorModules/Base/CurveEditor.cs
  ShadowShardEditor/Assets/EditorGUIPlus/EditorModules/Base/ObjectEditor.cs
  ShadowShardEditor/Assets/EditorGUIPlus/EditorModules/Base/PopupEditor.cs
  ShadowShardEditor/Assets/EditorGUIPlus/EditorModules/Base/SliderEditor.cs
  ShadowShardEditor/Assets/EditorGUIPlus/EditorModules/Base/SliderIntEditor.cs
  ShadowShardEditor/Assets/EditorGUIPlus/EditorModules/Base/TextEditor.cs
  ShadowShardEditor/Assets/EditorGUIPlus/EditorModules/Base/TextureEditor.cs
  ShadowShardEditor/Assets/EditorGUIPlus/EditorModules/Base/ToggleEditor.cs
  ShadowShardEditor/Assets/EditorGUIPlus/EditorModules/Base/VectorEditor.cs
  ShadowShardEditor/Assets/EditorGUIPlus/EditorModules/Base/VectorIntEditor.cs
  ShadowShardEditor/Assets/EditorGUIPlus/EditorModules/PropertyBased/SliderEditor.cs
  ShadowShardEditor/Assets/EditorGUIPlus/EditorModules/PropertyBased/SliderIntEditor.cs
  ShadowShardEditor/Assets/EditorGUIPlus/MaterialEditor/MaterialEditorGUIPlus.cs
Labels: enhancement

#53 Maxim moskalyk/8 editor auto drawer
  ShadowShardEditor/Assets/EditorGUIPlus/BaseEditorGUIPlus.cs
  ShadowShardEditor/Assets/EditorGUIPlus/EditorGUIPlus.cs
  ShadowShardEditor/Assets/EditorGUIPlus/EditorModules/Base/PopupEditor.cs
  ShadowShardEditor/Assets/EditorGUIPlus/EditorModules/FieldDrawer.cs
  ShadowShardEditor/Assets/EditorGUIPlus/EditorModules/FieldDrawer.cs.meta
  ShadowShardEditor/Assets/EditorGUIPlus/EditorModules/PropertyBased/ObjectEditor.cs
  ShadowShardEditor/Assets/ManualTesting/StandardEditor/Code/Data.meta
  ShadowShardEditor/Assets/ManualTesting/StandardEditor/Code/Data/TestSciptableObject.cs
  ShadowShardEditor/Assets/ManualTesting/StandardEditor/Code/Data/TestSciptableObject.cs.meta
  ShadowShardEditor/Assets/ManualTesting/StandardEditor/Code/Editor/TestStandardEditorWindow.cs
  ShadowShardEditor/Assets/ManualTesting/StandardEditor/Data/TestData.asset
  ShadowShardEditor/ProjectSettings/ProjectSettings.asset
Labels: enhancement, feature
